services:
  flask-app:
    image: python:3.9-slim
    container_name: flask-server
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    working_dir: /app
    command: |
      bash -c "pip install -r requirements.txt && flask --app app run"
    networks:
      - app-network

  node-app:
    image: node:22-slim
    container_name: node-server
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: |
      bash -c "npm install && npm run dev"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
